# Generated by Django 5.0.3 on 2024-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_blog_likes_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
